scripts:
  - name: Fix permissions
    script: chmod +x gradlew
  - name: Build Kotlin Framework
    script: |
      # On nettoie et on compile uniquement ce qui est vital
      ./gradlew :composeApp:assembleDebug \
        -Pkotlin.native.ignoreDisabledTargets=true \
        -Pcompose.ios.resources.targetArchs="arm64;x86_64" \
        --no-daemon --stacktrace
  - name: Build iOS App
    script: |
      xcodebuild -project iosApp/iosApp.xcodeproj \
        -scheme iosApp \
        -configuration Debug \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 15' \
        build CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO

workflows:
  ios-kmp-workflow:
    name: Build iOS MbanguKMP
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Build Kotlin Framework
        script: ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
      - name: Build iOS App
        script: |
          xcodebuild -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build CODE_SIGNING_ALLOWED=NO
    artifacts:
      - iosApp/build/Release-iphonesimulator/*.app

#workflows:
#  ios-build:
#    name: Build iOS Bonjour
#    instance_type: mac_mini_m2
#    scripts:
#      - name: Build iOS App
#        script: |
#          ./gradlew :composeApp:assembleDebug
#          xcodebuild -project iosApp/iosApp.xcodeproj \
#                     -scheme iosApp \
#                     -configuration Debug \
#                     -sdk iphonesimulator \
#                     build CODE_SIGNING_ALLOWED=NO
#    artifacts:
#      - iosApp/build/Release-iphonesimulator/*.app